import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col w-screen max-w-2xl py-8">{children}</div>
  );
}
